export const DONOR_LOGIN = 'LOGIN';
export const DONOR_LOGOUT = 'LOGOUT';

export const SET_CURRENT_CHARITIES = 'SET_CURRENT_CHARITIES';

export const SET_CATEGORIES = 'SET_CATEGORIES';

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTION = 'GET_TRANSACTION';

export const SET_BASKET_ITEMS = 'SET_BASKET_ITEMS';
export const CLEAR_BASKET_ITEMS = 'CLEAR_BASKET_ITEMS';

export const RESET_GIVING_HISTORY = 'RESET_GIVING_HISTORY';