export const DONOR_LOGIN = 'LOGIN';
export const DONOR_LOGOUT = 'LOGOUT';

export const GET_CHARITIES = 'GET_CHARITIES';
export const SET_CHARITIES = 'SET_CHARITIES';

export const RESET_CATEGORIES = 'RESET_CATEGORIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY = 'GET_CATEGORY';

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTION = 'GET_TRANSACTION';

export const SET_BASKET_ITEMS = 'SET_BASKET_ITEMS';
export const CLEAR_BASKET_ITEMS = 'CLEAR_BASKET_ITEMS';
