export const types = {
    UPDATE_LOCALE: "UPDATE_LOCALE",

    SET_DONOR: 'SET_DONOR',
    CLEAR_DONOR: 'CLEAR_DONOR',

    SET_CATEGORIES: 'SET_CATEGORIES',
    SET_CURRENT_CATEGORY: 'SET_CURRENT_CATEGORY',

    SET_CURRENT_CHARITIES: "SET_CURRENT_CHARITIES",
    APPEND_CURRENT_CHARITIES: "APPEND_CURRENT_CHARITIES",

    SET_BASKET_ITEMS: "SET_BASKET_ITEMS",
    CLEAR_BASKET_ITEMS: "CLEAR_BASKET_ITEMS",

    SET_COMPLETED_BASKET_ITEMS: "SET_COMPLETED_BASKET_ITEMS",

    SET_TOP_CHARITIES: "SET_TOP_CHARITIES",

    SET_GIVING_HISTORY: "SET_GIVING_HISTORY"
};

